### PR TITLE
Added support for streaming the bz2 file

### PR DESCRIPTION
**Pull request by mcassiano**
So it's not necessary to extract the whole file first.

### CODE REVIEW

**Comment by spencermountain** [comment]
FANCY!
:heart_eyes_cat: 
thanks!

**Comment by spencermountain** [comment]
ahhh this is the best ever.

**Comment by mcassiano** [comment]
sure man! 💃

**Comment by spencermountain** [comment]
hey, i updated the docs, and passed in the .bz2, and it's doing something, but isn't spitting-out in the xml.on('endElement: page') events. could you take a look?

**Comment by mcassiano** [comment]
Did you use "node index.js ./afwiki-latest-pages-articles.xml.bz2"? Try removing the "./" and passing in only the filename.

**Comment by spencermountain** [comment]
ah, got it.
:cake:

**Comment by mcassiano** [comment]
Did you notice some entries missing in the database? Some of them are printed by the script but I can't find them there.

**Comment by spencermountain** [comment]
aye, no. I did increase the db.close() timeout, any chance they're at the bottom of the xml?

**Comment by mcassiano** [comment]
probably not, im streaming a 1.2gb file (never actually finished processing since this keep happening)

**Pull request merged**
